MvcProjesi/Controllers/AdminLanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MvcProjesi.Controllers
{
    public class AdminLanguageController : Controller
    {
        // GET: AdminLanguage
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);
            }

            HttpCookie cookiee = new HttpCookie("language");
            cookiee.Value = languageSelect;
            Response.Cookies.Add(cookiee);
            
            return RedirectToAction("Index");
        }
    }
}

MvcProjesi/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MvcProjesi.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);
            }

            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageSelect;
            Response.Cookies.Add(cookie);

            return View("Index");
        }
    }
}

MvcProjesi/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Arşiv</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Arşiv", "Admin", "Uyelik", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Ana_Sayfa, "Admin", "Uyelik")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Tüm_Makaleler, "AdminMakaleler", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Hakkımda, "AdminHakkimda", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Tüm_Yorumlar, "AdminTumyorumlar", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Üyeleri_listele, "Uyelistesi","Uyelik")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Dil_Secimi, "Index", "AdminLanguage")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Çıkış_Yap, "Index","Home")</li>
                    
                </ul>
                 
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="float:right">Uye Id :@Session["uyeID"]</p>
            <p>&copy; @DateTime.Now.Year - Arşiv projesi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <!--Ajax işlemleri için gereken dosyamızı burada tüm sayfalarda kullanılacak şekilde tanıttık.
        Ayrıca dosyanın orijinal yolunu değil, bizim belirlediğimiz ~/bundles/jquery-unobtrusive
        yolunun kullanıldığına dikkat edin.-->
    @Scripts.Render("~/bundles/jquery-unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Arşiv</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(MvcProjesi.Resources.Home.Arşiv, "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Ana_Sayfa, "Index", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Hakkımda, "About", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Tüm_Makaleler, "TumMakaleler", "Home")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Admin_Girişi, "UyeGiris", "Uyelik")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Yeni_Üyelik, "YeniUyelik", "Uyelik")</li>
                    <li>@Html.ActionLink(MvcProjesi.Resources.Home.Dil_Secimi, "Index", "Language")</li>
                </ul>
                 
                </div>
            </div>
        </div>
     
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Arşiv projesi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <!--Ajax işlemleri için gereken dosyamızı burada tüm sayfalarda kullanılacak şekilde tanıttık.
        Ayrıca dosyanın orijinal yolunu değil, bizim belirlediğimiz ~/bundles/jquery-unobtrusive
        yolunun kullanıldığına dikkat edin.-->
    @Scripts.Render("~/bundles/jquery-unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>